### ISSUE TITLE
Query did not return a unique result in saveTestSuite method

### ISSUE THREAD

**Issue by kgevorkyan** [diktat-static-analysis/save-cloud#224]
Suppose we have several test suites with the same name, like in `save/examples`: `DocsCheck` repeated twice.

After first execution of  `uploadStandardTestSuite` the data will be stored in DB, however, if we will call `uploadStandardTestSuite` one more time, then will observe exception in `saveTestSuite()`:
```bash
org.springframework.dao.IncorrectResultSizeDataAccessException: query did not return a unique result: 2; nested exception is javax.persistence.NonUniqueResultException: query did not return a unique result: 2
```
Within the one project, it most likely incorrect structure of tests - test suites names shouldn't be repeated 

But in case when we have multiple projects, test suite names could be repeated - in this case we probably should compare records by some additional column, e.g. - `project`

**Comment by petertrr** [comment]
In `TestSuiteService.saveTestSuites()` we have now `distinctBy` and query by example with all fields (except for `description`), so this issue should be resolved.
