### ISSUE TITLE
Functionality of updating project's name and the description 

### ISSUE THREAD

**Issue by akuleshov7** [diktat-static-analysis/save-cloud#282]
We should be able to update this on the frontend side
![image](https://user-images.githubusercontent.com/58667063/135458675-63d602d3-2eb9-4cd2-8938-ce1e89876f97.png)

**Comment by petertrr** [comment]
Also (maybe in a separate issue) we may want to fix a certain git URL per project instead of manually inputting it from ProjectView. Then, we should be able to edit it too.

**Comment by kgevorkyan** [comment]
Also, If no git url is povided, probably we should disable this mod at all? Until user won't update git url
