### ISSUE TITLE
Add spring security to save

### ISSUE THREAD

**Issue by akuleshov7** [diktat-static-analysis/save-cloud#314]
```
        add("implementation", "org.springframework.boot:spring-boot-starter-security:${Versions.springBoot}")

```

**Comment by petertrr** [comment]
An old related issue is #34

**Comment by petertrr** [comment]
Related tasks:
* Describe is `save-deploy` how to configure firewall rules to allow external access only to nginx (on default 80/443 ports)
* Describe in `save-deploy` how to secure hosted save-cloud with HTTPS
