### ISSUE TITLE
Agent: Try to use coroutines native-mt version

### ISSUE THREAD

**Issue by petertrr** [diktat-static-analysis/save-cloud#315]
Now agent is signle-threaded and heartbeats are not sent while SAVE is executed.
Otherwise, we'll need to make processBuilder's `exec` method properly `suspend`able - i.e. it should yield and poll process status.

**Comment by akuleshov7** [comment]
That shouldbe easy, but I am afraid that Vlad won't be able to do this ...

**Comment by petertrr** [comment]
Actually, ktor already has `native-mt` version as its dependency, and we are using it as a transitive one. However, we are not specifying threads explicitly, and therefore everything runs in a single-threaded context. 
Related issue https://github.com/diktat-static-analysis/save/issues/331 to make API of ProcessBuiler more convenient for usage. The question that still needs to be answered - if current implementation of `exec` is called from a coroutine, can timer and process run in different threads?
