### ISSUE TITLE
If the test execution is in the PENDING status we should not show our awesome gif with cat

### ISSUE THREAD

**Issue by akuleshov7** [diktat-static-analysis/save-cloud#418]
Right now when tests are not discovered yet, but the status of run is PENDING we show the gif "TESTS NOT FOUND!"
We should write someting like "Loading" instead

**Comment by kgevorkyan** [comment]
Maybe under this issue it also will be possible to change Agent ID's from `null` to something meanable when execution have status `PENDING`?

![bug](https://user-images.githubusercontent.com/26010098/143218763-394168a3-0f8c-48b0-bc13-b6bbc50df9ef.PNG)
