### ISSUE TITLE
Save cloud not able to get an debug info in case, when test suite name contain whitespaces

### ISSUE THREAD

**Issue by kgevorkyan** [diktat-static-analysis/save-cloud#422]
That's not working for case when suite name have whitespace

![Capture](https://user-images.githubusercontent.com/26010098/143245542-4b2e7c97-e004-4738-8d82-369bb67a978b.PNG)

**Comment by petertrr** [comment]
May be fixed by #453 ?

**Comment by kgevorkyan** [comment]
Yes, tested, #453 fixed it
