### ISSUE TITLE
Inability of proper accessing to the executable files, if they aren't located in the root directory in standard mode

### ISSUE THREAD

**Issue by kgevorkyan** [diktat-static-analysis/save-cloud#436]
If executable files in standard mode aren't located in the root, it won't be possible to provide valid execution

**Comment by petertrr** [comment]
But we always place uploaded files in the root, right? So this is true only if executable files are inside the repo, which should never happen for standard test suites, at least after we implement #431

**Comment by kgevorkyan** [comment]
Yes, user provided files we upload always in the root

**Comment by akuleshov7** [comment]
After implementing a support for archives, we don't need to have binaries in the repository with tests
