### ISSUE TITLE
Numbers are not properly calculated again

### ISSUE THREAD

**Issue by akuleshov7** [diktat-static-analysis/save-cloud#469]
![image](https://user-images.githubusercontent.com/58667063/145281394-71c97352-cdd5-4b0b-bc54-d1ad168f2ea8.png)

http://saveourtool.com/#/NIST.gov/PMD%20and%20Juliet/history/execution/56

**Comment by petertrr** [comment]
The error is on ExecutionView exclusively; numbers are present in the DB and can be correctly seen on HistoryView

**Comment by petertrr** [comment]
```
GET http://saveourtool.com/api/testExecutions/count?executionId=56 404 (Not Found)
```
The correct endpoint is `api/testExecution/count`
